import { PDFTool } from '@/types/pdf';

export const ALL_TOOLS: PDFTool[] = [
  // ==========================================
  // 1. 📄 DOCUMENT & PDF POWERHOUSE (26 tools)
  // ==========================================
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    slug: 'merge',
    description: 'Combine multiple PDF files into one single organized document in your desired order.',
    category: 'organize',
    suite: 'pdf',
    icon: 'Layers',
    color: '#ef4444',
    gradient: 'from-rose-500 to-red-600',
    popular: true,
    badge: 'Popular',
  },
  {
    id: 'multi-organize',
    name: 'Multi-Document Lightbox',
    slug: 'multi-organize',
    description: 'Drop 2-10 documents into a visual lightbox. Reorder, rotate, delete, and assemble pages into 1 master PDF.',
    category: 'organize',
    suite: 'pdf',
    icon: 'LayoutGrid',
    color: '#f59e0b',
    gradient: 'from-amber-500 to-orange-600',
    popular: true,
    badge: 'Multi-Doc',
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    slug: 'split',
    description: 'Separate one page or a whole set for easy conversion into independent PDF files.',
    category: 'organize',
    suite: 'pdf',
    icon: 'Scissors',
    color: '#f97316',
    gradient: 'from-orange-500 to-amber-600',
    popular: true,
  },
  {
    id: 'organize-pdf',
    name: 'Organize PDF',
    slug: 'organize',
    description: 'Sort, reorder, delete, rotate, and duplicate pages visually with a drag-and-drop grid.',
    category: 'organize',
    suite: 'pdf',
    icon: 'LayoutGrid',
    color: '#f59e0b',
    gradient: 'from-amber-500 to-yellow-600',
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    slug: 'rotate',
    description: 'Rotate your PDF pages 90, 180, or 270 degrees. Save individual or all pages permanently.',
    category: 'organize',
    suite: 'pdf',
    icon: 'RotateCw',
    color: '#84cc16',
    gradient: 'from-lime-500 to-green-600',
  },
  {
    id: 'crop-pdf',
    name: 'Crop PDF',
    slug: 'crop',
    description: 'Trim unwanted white margins, headers, and footers with live interactive bounding box preview.',
    category: 'organize',
    suite: 'pdf',
    icon: 'Crop',
    color: '#10b981',
    gradient: 'from-emerald-500 to-teal-600',
    badge: 'Precision',
  },
  {
    id: 'form-builder',
    name: 'PDF Form Builder & AcroForms',
    slug: 'form-builder',
    description: 'Add interactive fillable text fields, checkboxes, dropdown menus, and digital signature boxes to any PDF.',
    category: 'edit',
    suite: 'pdf',
    icon: 'FormInput',
    color: '#6366f1',
    gradient: 'from-indigo-600 to-purple-600',
    popular: true,
    badge: 'Interactive',
  },
  {
    id: 'bates-numbering',
    name: 'Bates Numbering & Stamping',
    slug: 'bates-numbering',
    description: 'Enterprise and legal document discovery indexing with sequential prefixes, padded digits, and margins.',
    category: 'edit',
    suite: 'pdf',
    icon: 'Hash',
    color: '#8b5cf6',
    gradient: 'from-violet-600 to-indigo-600',
    badge: 'Legal',
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    slug: 'compress',
    description: 'Reduce file size while maintaining maximum PDF quality. Extreme, recommended, or light modes.',
    category: 'optimize',
    suite: 'pdf',
    icon: 'Minimize2',
    color: '#06b6d4',
    gradient: 'from-cyan-500 to-blue-600',
    popular: true,
    badge: 'High Speed',
  },
  {
    id: 'repair-pdf',
    name: 'Repair Corrupted PDF',
    slug: 'repair',
    description: 'Recover corrupted or damaged PDF files by reconstructing cross-reference tables and unclosed streams.',
    category: 'optimize',
    suite: 'pdf',
    icon: 'Wrench',
    color: '#0284c7',
    gradient: 'from-sky-500 to-indigo-600',
    badge: 'Recovery',
  },
  {
    id: 'edit-pdf',
    name: 'Edit PDF (Canvas Studio)',
    slug: 'edit',
    description: 'Add text, shapes, freehand ink, highlights, images, sticky notes, and stamps to your PDF.',
    category: 'edit',
    suite: 'pdf',
    icon: 'FileEdit',
    color: '#3b82f6',
    gradient: 'from-blue-600 to-indigo-700',
    popular: true,
    badge: 'Studio',
  },
  {
    id: 'watermark-pdf',
    name: 'Watermark PDF',
    slug: 'watermark',
    description: 'Stamp an image or text over your PDF in seconds. Customize typography, transparency, and position.',
    category: 'edit',
    suite: 'pdf',
    icon: 'Stamp',
    color: '#6366f1',
    gradient: 'from-indigo-500 to-purple-600',
  },
  {
    id: 'page-numbers',
    name: 'Page Numbers',
    slug: 'page-numbers',
    description: 'Add page numbers with customized formatting, position, margins, and typography styling.',
    category: 'edit',
    suite: 'pdf',
    icon: 'Hash',
    color: '#8b5cf6',
    gradient: 'from-violet-500 to-purple-600',
  },
  {
    id: 'sign-pdf',
    name: 'e-Sign PDF',
    slug: 'sign',
    description: 'Sign documents yourself or place signatures, initials, dates, and text with audit trails.',
    category: 'security',
    suite: 'pdf',
    icon: 'PenTool',
    color: '#a855f7',
    gradient: 'from-purple-600 to-fuchsia-600',
    popular: true,
    badge: 'Verified',
  },
  {
    id: 'ai-redact',
    name: 'AI Smart PII Redactor',
    slug: 'ai-redact',
    description: '1-Click auto-discovery & permanent vector blackout for Aadhaar, PAN, SSNs, credit cards, phones, and emails.',
    category: 'security',
    suite: 'pdf',
    icon: 'EyeOff',
    color: '#18181b',
    gradient: 'from-zinc-800 to-neutral-950',
    popular: true,
    badge: 'Auto Privacy',
  },
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    slug: 'protect',
    description: 'Encrypt your PDF with standard passwords and restrict unauthorized viewing or printing.',
    category: 'security',
    suite: 'pdf',
    icon: 'Lock',
    color: '#d946ef',
    gradient: 'from-fuchsia-500 to-pink-600',
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    slug: 'unlock',
    description: 'Remove password restrictions from your protected PDF so you can read and share freely.',
    category: 'security',
    suite: 'pdf',
    icon: 'Unlock',
    color: '#ec4899',
    gradient: 'from-pink-500 to-rose-600',
  },
  {
    id: 'redact-pdf',
    name: 'Manual Redact PDF',
    slug: 'redact',
    description: 'Permanently remove or blackout sensitive text, names, numbers, and private data.',
    category: 'security',
    suite: 'pdf',
    icon: 'EyeOff',
    color: '#18181b',
    gradient: 'from-zinc-700 to-neutral-900',
    badge: 'Privacy',
  },
  {
    id: 'flatten-pdf',
    name: 'Flatten PDF',
    slug: 'flatten',
    description: 'Bake all interactive form fields and annotations into static uneditable document streams.',
    category: 'security',
    suite: 'pdf',
    icon: 'FileCheck',
    color: '#64748b',
    gradient: 'from-slate-600 to-gray-800',
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    slug: 'jpg-to-pdf',
    description: 'Transform JPG, PNG, and WebP images to PDF. Adjust orientation, margins, and page sizes.',
    category: 'convert',
    suite: 'pdf',
    icon: 'Image',
    color: '#14b8a6',
    gradient: 'from-teal-500 to-emerald-600',
    popular: true,
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    slug: 'pdf-to-jpg',
    description: 'Extract every page of your PDF into crisp, high-resolution 300 DPI JPG/PNG images + ZIP.',
    category: 'convert',
    suite: 'pdf',
    icon: 'Images',
    color: '#059669',
    gradient: 'from-emerald-600 to-green-700',
  },
  {
    id: 'pdf-to-pptx',
    name: 'PDF to PowerPoint (PPTX)',
    slug: 'pdf-to-pptx',
    description: 'Convert PDF slide decks and presentations into editable widescreen 16:9 PowerPoint .pptx files.',
    category: 'convert',
    suite: 'pdf',
    icon: 'Presentation',
    color: '#ea580c',
    gradient: 'from-orange-600 to-amber-600',
    popular: true,
    badge: 'PPTX',
  },
  {
    id: 'pdf-to-docx',
    name: 'PDF to Word (DOCX)',
    slug: 'pdf-to-docx',
    description: 'Convert PDF documents and text into editable Microsoft Word (.docx) files with preserved headings.',
    category: 'convert',
    suite: 'pdf',
    icon: 'FileType',
    color: '#2563eb',
    gradient: 'from-blue-600 to-indigo-700',
    popular: true,
    badge: 'Word',
  },
  {
    id: 'pdf-to-text',
    name: 'PDF to Text / MD',
    slug: 'pdf-to-text',
    description: 'Extract raw text, paragraphs, and structured markdown from your document effortlessly.',
    category: 'convert',
    suite: 'pdf',
    icon: 'FileText',
    color: '#2563eb',
    gradient: 'from-blue-500 to-cyan-600',
  },
  {
    id: 'ocr-pdf',
    name: 'OCR Searchable PDF',
    slug: 'ocr',
    description: 'Convert scanned PDFs and paper documents into fully searchable, selectable PDF documents with text layer.',
    category: 'smart',
    suite: 'pdf',
    icon: 'ScanText',
    color: '#7c3aed',
    gradient: 'from-violet-600 to-indigo-700',
    badge: 'Sandwich PDF',
  },
  {
    id: 'compare-pdf',
    name: 'Compare PDF (Diff)',
    slug: 'compare',
    description: 'Spot differences between two revisions of a PDF with side-by-side visual diffing.',
    category: 'smart',
    suite: 'pdf',
    icon: 'Columns2',
    color: '#ea580c',
    gradient: 'from-amber-600 to-orange-700',
  },

  // ==========================================
  // 2. 🤖 NEXT-GEN AI FILE INTELLIGENCE (5 tools)
  // ==========================================
  {
    id: 'invoice-extractor',
    name: 'AI Invoice & Receipt to Excel',
    slug: 'invoice-extractor',
    description: 'Extract vendor, dates, tax breakdown, and all line-item tables from invoices into structured Excel & CSV.',
    category: 'ai',
    suite: 'ai',
    icon: 'Receipt',
    color: '#10b981',
    gradient: 'from-emerald-500 to-teal-600',
    popular: true,
    badge: 'Financial AI',
  },
  {
    id: 'chat-file',
    name: 'Chat with Any File',
    slug: 'chat-file',
    description: 'Upload PDF, DOCX, CSV, Code or Images and talk to TheWebVale AI with fast multimodal streaming responses.',
    category: 'ai',
    suite: 'ai',
    icon: 'MessageSquareText',
    color: '#7c3aed',
    gradient: 'from-violet-600 to-indigo-700',
    popular: true,
    badge: 'TheWebVale AI',
  },
  {
    id: 'ai-table-extractor',
    name: 'AI Smart Table Extractor',
    slug: 'ai-table-extractor',
    description: 'Turn paper receipts, invoices, and screenshot tables into clean, structured Excel & CSV spreadsheets.',
    category: 'ai',
    suite: 'ai',
    icon: 'TableProperties',
    color: '#10b981',
    gradient: 'from-emerald-500 to-teal-600',
    popular: true,
    badge: 'Vision AI',
  },
  {
    id: 'ai-file-renamer',
    name: 'Batch File Smart Renamer',
    slug: 'ai-file-renamer',
    description: 'Drop 50+ messy filenames and let AI deduce document context and generate clean naming structures.',
    category: 'ai',
    suite: 'ai',
    icon: 'Tags',
    color: '#f59e0b',
    gradient: 'from-amber-500 to-orange-600',
    badge: 'Batch AI',
  },
  {
    id: 'ai-audio-summary',
    name: 'Meeting & Audio AI Summarizer',
    slug: 'ai-audio-summary',
    description: 'Transcribe audio memos & meetings to executive summaries, key decisions, and action item checklists.',
    category: 'ai',
    suite: 'ai',
    icon: 'Mic',
    color: '#ef4444',
    gradient: 'from-rose-500 to-red-600',
    popular: true,
    badge: 'Audio AI',
  },

  // ==========================================
  // 3. 🎨 IMAGE STUDIO & VISUAL MEDIA (7 tools)
  // ==========================================
  {
    id: 'image-converter',
    name: 'Universal Image Converter',
    slug: 'image-converter',
    description: 'Bi-directional batch conversion: HEIC, WEBP, PNG, JPG, AVIF, ICO, SVG, and BMP in your browser.',
    category: 'image',
    suite: 'image',
    icon: 'RefreshCw',
    color: '#06b6d4',
    gradient: 'from-cyan-500 to-blue-600',
    popular: true,
    badge: 'Zero Upload',
  },
  {
    id: 'image-compress',
    name: 'Smart Image Compressor',
    slug: 'image-compress',
    description: 'Visual slider with split-screen compare + "Target File Size" mode (e.g. compress under 500 KB).',
    category: 'image',
    suite: 'image',
    icon: 'Sliders',
    color: '#10b981',
    gradient: 'from-emerald-500 to-teal-600',
    popular: true,
    badge: 'Smart Sizer',
  },
  {
    id: 'bg-remover',
    name: 'AI Background Remover',
    slug: 'bg-remover',
    description: '100% In-browser cutout engine for portraits & product photos. Zero server uploads or API limits.',
    category: 'image',
    suite: 'image',
    icon: 'Wand2',
    color: '#ec4899',
    gradient: 'from-pink-500 to-rose-600',
    popular: true,
    badge: '100% Client AI',
  },
  {
    id: 'image-resizer',
    name: 'Asset & Format Resizer',
    slug: 'image-resizer',
    description: 'One-click crops for Instagram (1:1, 9:16), YouTube (16:9), Twitter, Passport photos & custom px.',
    category: 'image',
    suite: 'image',
    icon: 'Maximize2',
    color: '#f59e0b',
    gradient: 'from-amber-500 to-orange-600',
  },
  {
    id: 'exif-cleaner',
    name: 'EXIF Privacy Scrubber',
    slug: 'exif-cleaner',
    description: 'Inspect camera lens, shutter, GPS map coordinates; 1-click strip all tracking metadata before sharing.',
    category: 'image',
    suite: 'image',
    icon: 'ShieldAlert',
    color: '#8b5cf6',
    gradient: 'from-purple-500 to-indigo-600',
    badge: 'Privacy',
  },
  {
    id: 'svg-optimizer',
    name: 'SVG Optimizer & Vectorizer',
    slug: 'svg-optimizer',
    description: 'Clean bloated Illustrator/Figma SVG code and vectorize bitmap raster images into crisp SVG paths.',
    category: 'image',
    suite: 'image',
    icon: 'Code2',
    color: '#3b82f6',
    gradient: 'from-blue-500 to-cyan-600',
  },
  {
    id: 'color-palette',
    name: 'Color Palette Extractor',
    slug: 'color-palette',
    description: 'Extract dominant palettes, HEX, RGB, HSL, Tailwind names & WCAG contrast compliance from any image.',
    category: 'image',
    suite: 'image',
    icon: 'Palette',
    color: '#f43f5e',
    gradient: 'from-rose-500 to-pink-600',
  },

  // ==========================================
  // 4. 📊 SPREADSHEETS & DOCUMENTS (6 tools)
  // ==========================================
  {
    id: 'csv-json-excel',
    name: 'CSV / Excel / JSON Matrix',
    slug: 'csv-json-excel',
    description: 'Bi-directional spreadsheet converter with delimiter auto-detection, field mapping, and live data table.',
    category: 'data',
    suite: 'data',
    icon: 'Table',
    color: '#10b981',
    gradient: 'from-emerald-500 to-green-600',
    popular: true,
    badge: 'Fast Matrix',
  },
  {
    id: 'csv-cleaner',
    name: 'CSV Cleaner & Deduplicator',
    slug: 'csv-cleaner',
    description: 'Trim whitespace, remove duplicate rows, format dates, normalize text case, and fill missing values.',
    category: 'data',
    suite: 'data',
    icon: 'Sparkles',
    color: '#0284c7',
    gradient: 'from-sky-500 to-blue-600',
  },
  {
    id: 'data-visualizer',
    name: 'Instant Data Visualizer',
    slug: 'data-visualizer',
    description: 'Drop CSV or JSON: auto-detect numeric columns & render customizable Bar, Line, Area, Pie & Donut charts.',
    category: 'data',
    suite: 'data',
    icon: 'BarChart3',
    color: '#6366f1',
    gradient: 'from-indigo-500 to-purple-600',
    popular: true,
  },
  {
    id: 'docx-to-markdown',
    name: 'Word DOCX to Markdown/HTML',
    slug: 'docx-to-markdown',
    description: 'Convert DOCX files into clean Markdown or semantic HTML with preserved tables, headings, and lists.',
    category: 'data',
    suite: 'data',
    icon: 'FileType',
    color: '#2563eb',
    gradient: 'from-blue-600 to-indigo-700',
  },
  {
    id: 'diff-checker',
    name: 'Document & Code Diff Checker',
    slug: 'diff-checker',
    description: 'Visual side-by-side & unified diff viewer. Spot additions, deletions, and inline character edits.',
    category: 'data',
    suite: 'data',
    icon: 'GitCompare',
    color: '#f97316',
    gradient: 'from-orange-500 to-amber-600',
  },
  {
    id: 'epub-converter',
    name: 'eBook & EPUB Studio',
    slug: 'epub-converter',
    description: 'Read EPUB eBooks in-browser, extract text & chapters to Markdown/PDF, or package Markdown into EPUB.',
    category: 'data',
    suite: 'data',
    icon: 'BookOpen',
    color: '#d946ef',
    gradient: 'from-fuchsia-500 to-pink-600',
  },

  // ==========================================
  // 5. 🎬 AUDIO & VIDEO FAST TOOLS (5 tools)
  // ==========================================
  {
    id: 'video-compress',
    name: 'Video Compressor & Resizer',
    slug: 'video-compress',
    description: 'Compress video files client-side. Downscale resolution (1080p, 720p, 480p) & lower bitrate without uploading.',
    category: 'media',
    suite: 'media',
    icon: 'Video',
    color: '#ef4444',
    gradient: 'from-rose-500 to-red-600',
    popular: true,
  },
  {
    id: 'video-to-gif',
    name: 'Video to Animated GIF',
    slug: 'video-to-gif',
    description: 'Encode video clips into high-framerate animated GIFs with 256-color palette quantization.',
    category: 'media',
    suite: 'media',
    icon: 'Clapperboard',
    color: '#f59e0b',
    gradient: 'from-amber-500 to-yellow-600',
    popular: true,
    badge: 'GIF',
  },
  {
    id: 'audio-extractor',
    name: 'Audio Extractor & Converter',
    slug: 'audio-extractor',
    description: 'Rip audio tracks from video (MP4/WebM to WAV/MP3) or convert audio sample rates and channels.',
    category: 'media',
    suite: 'media',
    icon: 'Volume2',
    color: '#14b8a6',
    gradient: 'from-teal-500 to-emerald-600',
  },
  {
    id: 'audio-trimmer',
    name: 'Audio Waveform Trimmer',
    slug: 'audio-trimmer',
    description: 'Interactive audio waveform visualizer. Cut, trim, fade-in, fade-out, and export clean audio clips.',
    category: 'media',
    suite: 'media',
    icon: 'Activity',
    color: '#8b5cf6',
    gradient: 'from-violet-500 to-purple-600',
  },
  {
    id: 'subtitle-editor',
    name: 'Subtitle SRT/VTT Creator',
    slug: 'subtitle-editor',
    description: 'Interactive subtitle timing editor with live video playback sync. Convert between SRT, VTT, and JSON.',
    category: 'media',
    suite: 'media',
    icon: 'Subtitles',
    color: '#06b6d4',
    gradient: 'from-cyan-500 to-blue-600',
  },

  // ==========================================
  // 6. 📦 ARCHIVE & FILE EXTRACTION (3 tools)
  // ==========================================
  {
    id: 'unarchiver',
    name: 'Universal Unarchiver',
    slug: 'unarchiver',
    description: 'Extract ZIP, TAR, GZ, TGZ archives in your browser with directory tree browser and selective file preview.',
    category: 'archive',
    suite: 'archive',
    icon: 'FolderArchive',
    color: '#f97316',
    gradient: 'from-orange-500 to-amber-600',
    popular: true,
    badge: 'ZIP/TAR/GZ',
  },
  {
    id: 'zip-creator',
    name: 'Fast ZIP Creator',
    slug: 'zip-creator',
    description: 'Create multi-file ZIP packages with configurable compression levels and folder trees.',
    category: 'archive',
    suite: 'archive',
    icon: 'FileArchive',
    color: '#6366f1',
    gradient: 'from-indigo-500 to-purple-600',
  },
  {
    id: 'file-splitter',
    name: 'Large File Splitter & Joiner',
    slug: 'file-splitter',
    description: 'Split massive files into email/Discord friendly chunks (e.g. 25MB) and re-join them with checksum check.',
    category: 'archive',
    suite: 'archive',
    icon: 'Split',
    color: '#059669',
    gradient: 'from-emerald-600 to-green-700',
  },

  // ==========================================
  // 7. 🛡️ SECURITY & DEV TOOLS (5 tools)
  // ==========================================
  {
    id: 'burn-share',
    name: 'Burn-After-Reading Share',
    slug: 'burn-share',
    description: 'End-to-end zero-knowledge client encrypted file transfer. Decrypts once in browser and self-destructs.',
    category: 'security',
    suite: 'security',
    icon: 'Flame',
    color: '#ef4444',
    gradient: 'from-red-500 to-rose-600',
    popular: true,
    badge: 'Zero-Knowledge',
  },
  {
    id: 'qr-barcode',
    name: 'QR Code & Barcode Studio',
    slug: 'qr-barcode',
    description: 'Generate ISO-compliant styled QR codes with logo embedding & 1D retail/inventory barcodes (Code128, EAN).',
    category: 'security',
    suite: 'security',
    icon: 'QrCode',
    color: '#a855f7',
    gradient: 'from-purple-500 to-fuchsia-600',
    popular: true,
    badge: 'Scannable',
  },
  {
    id: 'hash-verifier',
    name: 'Checksum & Hash Verifier',
    slug: 'hash-verifier',
    description: 'Calculate SHA-256, SHA-512, SHA-1, MD5, and CRC32 in seconds. Compare against expected hash.',
    category: 'security',
    suite: 'security',
    icon: 'Hash',
    color: '#84cc16',
    gradient: 'from-lime-500 to-green-600',
  },
  {
    id: 'base64-studio',
    name: 'Base64 & Data URI Studio',
    slug: 'base64-studio',
    description: 'Convert files to Base64, Data URI, Hex strings, and back. Includes instant clipboard and HTML preview.',
    category: 'security',
    suite: 'security',
    icon: 'Binary',
    color: '#0284c7',
    gradient: 'from-sky-500 to-cyan-600',
  },
  {
    id: 'steganography',
    name: 'Image Steganography',
    slug: 'steganography',
    description: 'Hide confidential text and secret files invisibly inside PNG images with optional AES encryption.',
    category: 'security',
    suite: 'security',
    icon: 'EyeOff',
    color: '#18181b',
    gradient: 'from-zinc-700 to-neutral-900',
    badge: 'Stealth',
  },
];

// Alias for backward compatibility
export const PDF_TOOLS = ALL_TOOLS;
